name: CI
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hello Jacob
      run: echo Jacob
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm test
  